#!/usr/bin/env python3
"""
Visualize ONLY images with invalid/updated COCO annotations.

Expected dataset:
root/
  train/
    images...
    _annotations.json
  test/
    images...
    _annotations.json
  val/
    images...
    _annotations.json
  val_eval/
    images...
    _annotations.json
  val_split/
    images...
    _annotations.json
  basic_eval/
    images...
    _annotations.json

The script reads annotation_changes.csv generated by the annotation-cleaning
script and visualizes only affected images.

RED   = original invalid annotation
GREEN = corrected/clipped annotation
ORANGE = other valid annotation for context

The original dataset is never modified.
"""

import argparse
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

import cv2


ANNOTATION_FILE = "_annotations.json"


def parse_bbox(value):
    if not value:
        return None
    try:
        v = json.loads(value)
        if isinstance(v, list) and len(v) == 4:
            return [float(x) for x in v]
    except Exception:
        pass
    return None


def find_image(split_dir, filename):
    filename = str(filename).replace("\\", "/").lstrip("/")

    # Direct path
    p = split_dir / filename
    if p.is_file():
        return p

    # Flattened filename
    p = split_dir / Path(filename).name
    if p.is_file():
        return p

    # Recursive fallback
    matches = list(split_dir.rglob(Path(filename).name))
    return matches[0] if matches else None


def load_coco(split_dir):
    p = split_dir / ANNOTATION_FILE
    if not p.exists():
        print(f"WARNING: missing {p}")
        return None

    try:
        with open(p, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"WARNING: failed to read {p}: {e}")
        return None


def category_map(coco):
    return {
        c.get("id"): c.get("name", str(c.get("id")))
        for c in coco.get("categories", [])
    }


def draw_box(img, bbox, color, label, thickness=3):
    if bbox is None or len(bbox) != 4:
        return

    x, y, w, h = bbox
    x1 = int(round(x))
    y1 = int(round(y))
    x2 = int(round(x + w))
    y2 = int(round(y + h))

    cv2.rectangle(img, (x1, y1), (x2, y2), color, thickness)

    font = cv2.FONT_HERSHEY_SIMPLEX
    scale = 0.48
    text_thickness = 2

    (tw, th), base = cv2.getTextSize(
        label, font, scale, text_thickness
    )

    tx = max(0, min(x1, img.shape[1] - tw - 8))
    ty = y1 - 7

    if ty - th < 0:
        ty = min(img.shape[0] - 5, y1 + th + 8)

    cv2.rectangle(
        img,
        (tx, ty - th - 5),
        (tx + tw + 8, ty + base),
        color,
        -1,
    )

    cv2.putText(
        img,
        label,
        (tx + 4, ty),
        font,
        scale,
        (255, 255, 255),
        text_thickness,
        cv2.LINE_AA,
    )


def add_header(img, split, filename, changes):
    removed = sum(
        r.get("action", "").lower() == "removed"
        for r in changes
    )
    clipped = sum(
        r.get("action", "").lower() == "clipped"
        for r in changes
    )

    header_h = 85

    canvas = cv2.copyMakeBorder(
        img,
        header_h,
        0,
        0,
        0,
        cv2.BORDER_CONSTANT,
        value=(35, 35, 35),
    )

    font = cv2.FONT_HERSHEY_SIMPLEX

    cv2.putText(
        canvas,
        f"INVALID / UPDATED ANNOTATION | {split}",
        (15, 30),
        font,
        0.62,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )

    cv2.putText(
        canvas,
        f"{filename} | Issues: {len(changes)} | "
        f"Removed: {removed} | Clipped: {clipped}",
        (15, 63),
        font,
        0.45,
        (220, 220, 220),
        1,
        cv2.LINE_AA,
    )

    return canvas


def add_legend(img):
    h, w = img.shape[:2]

    box_w = min(470, max(320, w - 20))
    box_h = 72
    x = 10
    y = h - box_h - 10

    overlay = img.copy()
    cv2.rectangle(
        overlay,
        (x, y),
        (x + box_w, y + box_h),
        (25, 25, 25),
        -1,
    )

    img = cv2.addWeighted(overlay, 0.85, img, 0.15, 0)

    cv2.rectangle(
        img, (x + 12, y + 10), (x + 32, y + 30),
        (0, 0, 255), -1
    )
    cv2.putText(
        img, "Original invalid bbox",
        (x + 42, y + 27),
        cv2.FONT_HERSHEY_SIMPLEX, 0.46,
        (255, 255, 255), 1, cv2.LINE_AA
    )

    cv2.rectangle(
        img, (x + 12, y + 40), (x + 32, y + 60),
        (0, 200, 0), -1
    )
    cv2.putText(
        img, "Corrected / clipped bbox",
        (x + 42, y + 57),
        cv2.FONT_HERSHEY_SIMPLEX, 0.46,
        (255, 255, 255), 1, cv2.LINE_AA
    )

    return img


def main():
    parser = argparse.ArgumentParser(
        description="Visualize only images with invalid/updated COCO annotations."
    )

    parser.add_argument(
        "--root",
        required=True,
        help="Original dataset root",
    )

    parser.add_argument(
        "--report",
        required=True,
        help="Path to annotation_changes.csv",
    )

    parser.add_argument(
        "--out",
        required=True,
        help="Output visualization directory",
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Maximum affected images per split. 0 = all.",
    )

    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve()
    report = Path(args.report).expanduser().resolve()
    out = Path(args.out).expanduser().resolve()

    if not root.exists():
        print(f"ERROR: dataset root not found: {root}")
        sys.exit(1)

    if not report.exists():
        print(f"ERROR: report not found: {report}")
        sys.exit(1)

    # ------------------------------------------------------------------
    # Read changes report
    # ------------------------------------------------------------------

    affected = defaultdict(list)

    with open(report, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)

        for row in reader:
            split = row.get("split", "").strip()
            filename = row.get("image", "").strip()

            if split and filename:
                affected[(split, filename)].append(row)

    if not affected:
        print("No affected images found in annotation_changes.csv.")
        return

    print("=" * 80)
    print("INVALID ANNOTATION VISUALIZATION")
    print("=" * 80)
    print(f"Affected images: {len(affected)}")
    print()

    out.mkdir(parents=True, exist_ok=True)

    coco_cache = {}
    saved = 0
    missing = 0
    split_counts = defaultdict(int)

    # ------------------------------------------------------------------
    # Process only affected images
    # ------------------------------------------------------------------

    for (split, filename), changes in sorted(affected.items()):

        if args.limit and split_counts[split] >= args.limit:
            continue

        split_dir = root / split

        if split not in coco_cache:
            coco_cache[split] = load_coco(split_dir)

        coco = coco_cache[split]

        if coco is None:
            continue

        image_path = find_image(split_dir, filename)

        if image_path is None:
            print(f"[MISSING] {split}/{filename}")
            missing += 1
            continue

        img = cv2.imread(str(image_path))

        if img is None:
            print(f"[UNREADABLE] {image_path}")
            missing += 1
            continue

        categories = category_map(coco)

        # Find image ID in COCO.
        image_info = None

        for im in coco.get("images", []):
            if (
                im.get("file_name") == filename
                or Path(im.get("file_name", "")).name == Path(filename).name
            ):
                image_info = im
                break

        if image_info is None:
            print(f"[NO COCO IMAGE ENTRY] {split}/{filename}")
            missing += 1
            continue

        image_id = image_info.get("id")

        annotations = [
            a for a in coco.get("annotations", [])
            if a.get("image_id") == image_id
        ]

        changed_ids = {
            str(r.get("annotation_id", ""))
            for r in changes
        }

        # --------------------------------------------------------------
        # Draw other valid annotations for context.
        # --------------------------------------------------------------

        for ann in annotations:
            if str(ann.get("id", "")) in changed_ids:
                continue

            cls = categories.get(
                ann.get("category_id"),
                str(ann.get("category_id")),
            )

            draw_box(
                img,
                ann.get("bbox"),
                (0, 165, 255),
                f"{cls} | valid",
                thickness=2,
            )

        # --------------------------------------------------------------
        # Draw invalid / corrected annotations.
        # --------------------------------------------------------------

        for row in changes:

            original = parse_bbox(
                row.get("original_bbox", "")
            )

            corrected = parse_bbox(
                row.get("corrected_bbox", "")
            )

            issue = row.get("issue", "invalid")
            action = row.get("action", "")
            ann_id = row.get("annotation_id", "")

            # RED: exact original invalid bbox.
            if original is not None:
                draw_box(
                    img,
                    original,
                    (0, 0, 255),
                    f"INVALID | {issue} | ann {ann_id}",
                    thickness=4,
                )

            # GREEN: corrected bbox if the cleaner produced one.
            if corrected is not None and action.lower() == "clipped":
                draw_box(
                    img,
                    corrected,
                    (0, 200, 0),
                    "CORRECTED / CLIPPED",
                    thickness=4,
                )

        img = add_header(
            img,
            split,
            Path(filename).name,
            changes,
        )

        img = add_legend(img)

        split_out = out / split
        split_out.mkdir(parents=True, exist_ok=True)

        output_name = (
            Path(filename).stem + "_INVALID.jpg"
        )

        output_path = split_out / output_name

        ok = cv2.imwrite(
            str(output_path),
            img,
            [cv2.IMWRITE_JPEG_QUALITY, 95],
        )

        if ok:
            saved += 1
            split_counts[split] += 1
            print(f"[SAVED] {output_path}")
        else:
            print(f"[ERROR] Could not save {output_path}")

    print()
    print("=" * 80)
    print("DONE")
    print("=" * 80)
    print(f"Saved:   {saved}")
    print(f"Missing: {missing}")
    print()

    for split in sorted(split_counts):
        print(f"{split}: {split_counts[split]} images")

    print()
    print(f"Output folder: {out}")
    print()
    print("RED    = original invalid annotation")
    print("GREEN  = corrected/clipped annotation")
    print("ORANGE = other valid annotations")
    print()
    print("Original dataset was NOT modified.")


if __name__ == "__main__":
    main()
