"""Numeric track-ID parity test for LibreYOLO's OC-SORT port.

LibreYOLO's :class:`OCSortTracker` is a clean-room reimplementation of OC-SORT
(Cao et al., CVPR 2023). This test proves it reproduces the *original authors'*
reference implementation (noahcao/OC_SORT, MIT) frame-for-frame on identical
detection sequences.

Two layers:

* ``test_golden_parity`` (always runs) replays a committed golden fixture of the
  reference's per-frame output rows and asserts the port matches exactly. The
  fixture is generated by ``parity_ref/make_fixture.py`` against the reference.
* ``test_live_reference_parity`` (skipped unless the reference is importable)
  re-derives the reference outputs on the fly and compares, mirroring the
  pattern in ``test_ec_parity.py``. Point it at a checkout with
  ``OCSORT_REF_PATH=/path/to/ocsort_tracker`` (parent dir on ``sys.path``).

Both feed the same sequences to both trackers; OC-SORT is deterministic and both
assign IDs in creation order, so an exact per-frame row-set match is parity.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import numpy as np
import pytest

from libreyolo.tracking.config import OCSortConfig
from libreyolo.tracking.ocsort import OCSortTracker

pytestmark = pytest.mark.unit

GOLDEN_PATH = Path(__file__).parent / "data" / "ocsort_parity_golden.json"
IMG = [720, 1280]

# Hyperparameter sets used by the curated sequences below.
DEFAULT = dict(
    det_thresh=0.5, max_age=30, min_hits=3,
    iou_threshold=0.3, delta_t=3, inertia=0.2, use_byte=False,
)
BYTE = {**DEFAULT, "use_byte": True}


# --------------------------------------------------------------------------
# Deterministic detection-sequence generators (shared with the fixture maker)
# --------------------------------------------------------------------------


def _box(cx, cy, w, h):
    return [cx - w / 2, cy - h / 2, cx + w / 2, cy + h / 2]


def seq_linear(T=25):
    """Two objects, constant velocity, always detected."""
    frames = []
    for t in range(T):
        frames.append(np.array([
            _box(100 + 8 * t, 200, 40, 90) + [0.9],
            _box(900 - 6 * t, 400, 50, 110) + [0.85],
        ], dtype=float))
    return frames


def seq_crossing(T=30):
    """Two objects crossing paths (stresses observation-centric momentum)."""
    frames = []
    for t in range(T):
        frames.append(np.array([
            _box(100 + 20 * t, 300 + 6 * t, 45, 95) + [0.92],
            _box(700 - 20 * t, 300 + 6 * t, 45, 95) + [0.88],
        ], dtype=float))
    return frames


def seq_occlusion(T=30):
    """One object vanishes for frames 10-17 then returns (ORU / OCR)."""
    frames = []
    for t in range(T):
        dets = [_box(150 + 18 * t, 360, 48, 100) + [0.9]]
        if not (10 <= t <= 17):
            dets.append(_box(1100 - 15 * t, 250 + 4 * t, 40, 88) + [0.8])
        frames.append(np.array(dets, dtype=float))
    return frames


def seq_empty_and_sparse(T=20):
    """Frames with zero or one detection, with leading/trailing gaps."""
    frames = []
    for t in range(T):
        if t < 2 or t in (8, 9, 10) or t >= T - 2:
            frames.append(np.empty((0, 5), dtype=float))
        else:
            frames.append(np.array([_box(200 + 15 * t, 300, 50, 100) + [0.7]], dtype=float))
    return frames


def seq_noisy(seed, T=40, n_obj=5):
    """Multiple objects with box jitter, score jitter and random dropouts."""
    rng = np.random.default_rng(seed)
    pos = rng.uniform([100, 100], [1100, 600], size=(n_obj, 2))
    vel = rng.uniform(-12, 12, size=(n_obj, 2))
    size = rng.uniform([35, 80], [60, 130], size=(n_obj, 2))
    frames = []
    for _ in range(T):
        pos = pos + vel
        dets = []
        for i in range(n_obj):
            if rng.random() < 0.12:
                continue
            cx, cy = pos[i] + rng.normal(0, 1.5, size=2)
            w, h = size[i]
            score = float(np.clip(rng.normal(0.75, 0.18), 0.05, 0.99))
            dets.append(_box(cx, cy, w, h) + [score])
        frames.append(np.array(dets, dtype=float).reshape(-1, 5))
    return frames


def seq_lowscore(seed, T=35, n_obj=6):
    """Wide score spread straddling det_thresh to exercise BYTE recovery."""
    rng = np.random.default_rng(seed)
    pos = rng.uniform([100, 100], [1100, 600], size=(n_obj, 2))
    vel = rng.uniform(-10, 10, size=(n_obj, 2))
    size = rng.uniform([35, 80], [60, 130], size=(n_obj, 2))
    frames = []
    for _ in range(T):
        pos = pos + vel
        dets = []
        for i in range(n_obj):
            if rng.random() < 0.1:
                continue
            cx, cy = pos[i] + rng.normal(0, 1.5, size=2)
            w, h = size[i]
            score = float(np.clip(rng.normal(0.45, 0.25), 0.05, 0.99))
            dets.append(_box(cx, cy, w, h) + [score])
        frames.append(np.array(dets, dtype=float).reshape(-1, 5))
    return frames


def parity_sequences():
    """Ordered registry of ``(name, params, frames)`` parity scenarios."""
    seqs = [
        ("linear", DEFAULT, seq_linear()),
        ("crossing", DEFAULT, seq_crossing()),
        ("occlusion", DEFAULT, seq_occlusion()),
        ("empty_sparse", DEFAULT, seq_empty_and_sparse()),
        ("noisy0", DEFAULT, seq_noisy(0)),
        ("noisy1", DEFAULT, seq_noisy(1)),
        ("noisy2", DEFAULT, seq_noisy(2)),
        ("lowscore0_byte", BYTE, seq_lowscore(0)),
        ("lowscore1_byte", BYTE, seq_lowscore(1)),
    ]
    return seqs


# --------------------------------------------------------------------------
# Comparison helpers
# --------------------------------------------------------------------------


def _by_id(rows):
    """Frame output as ``{track_id: box[x1,y1,x2,y2]}``."""
    out = {}
    for r in rows:
        out[int(round(float(r[4])))] = np.asarray(r[:4], dtype=float)
    return out


def _assert_frame_parity(port_rows, ref_rows, ctx, atol=1e-2):
    """Same reported track IDs, with boxes agreeing to within ``atol`` pixels."""
    port, ref = _by_id(port_rows), _by_id(ref_rows)
    assert set(port) == set(ref), f"{ctx}: track IDs differ {set(port)} vs {set(ref)}"
    for tid in port:
        assert np.allclose(port[tid], ref[tid], atol=atol), (
            f"{ctx}: box for id {tid} differs {port[tid]} vs {ref[tid]}"
        )


def _port_outputs(params, frames):
    """Run OCSortTracker over a sequence, returning per-frame output rows."""
    tracker = OCSortTracker(config=OCSortConfig(**params))
    return [tracker._update_tracks(f.copy()) for f in frames]


# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------


def test_golden_parity():
    """The port reproduces the reference's recorded per-frame output exactly."""
    if not GOLDEN_PATH.exists():
        pytest.skip(f"golden fixture missing at {GOLDEN_PATH} (run make_fixture.py)")
    golden = json.loads(GOLDEN_PATH.read_text())
    by_name = {s["name"]: s for s in golden["sequences"]}

    seqs = parity_sequences()
    assert set(by_name) == {name for name, _, _ in seqs}, "fixture/sequence drift"

    for name, params, frames in seqs:
        outputs = _port_outputs(params, frames)
        ref_frames = by_name[name]["frames"]
        assert len(outputs) == len(ref_frames), name
        for t, (port_rows, ref_rows) in enumerate(zip(outputs, ref_frames)):
            _assert_frame_parity(port_rows, ref_rows, f"{name} frame {t}")


def _import_reference():
    """Import the original OCSort, or skip. Mirrors test_ec_parity.py."""
    ref_path = os.environ.get("OCSORT_REF_PATH")
    candidates = [ref_path] if ref_path else []
    # Convenience default: the scratch vendoring used during development.
    candidates.append(str(Path(__file__).resolve().parents[2] / "parity_ref"))
    for cand in candidates:
        if cand and (Path(cand) / "ocsort_tracker" / "ocsort.py").exists():
            sys.path.insert(0, cand)
            try:
                from ocsort_tracker.ocsort import OCSort
                return OCSort
            except ImportError:
                continue
    pytest.skip("original OC-SORT reference not found (set OCSORT_REF_PATH)")


def test_live_reference_parity():
    """Re-derive reference outputs live and compare to the port."""
    OCSort = _import_reference()
    for name, params, frames in parity_sequences():
        ref = OCSort(**params)
        port_outputs = _port_outputs(params, frames)
        for t, frame in enumerate(frames):
            ref_rows = ref.update(frame.copy(), IMG, IMG)
            _assert_frame_parity(port_outputs[t], ref_rows, f"{name} frame {t}")
